# This is a basic workflow to help you get started with Actions

name: CI Pipeline

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Code Style Check
        run: echo Code Style Check!

      # Runs a single command using the runners shell
      - name: Test
        run: echo Test!

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          npm install,
          echo Build.
          
      # Runs a set of commands using the runners shell
      - name: Deploy
        run: |
          npm install,
          echo Build.
